"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { PageHeading } from "@/components/page-heading";
import { AsyncForm, Badge, Modal, Panel } from "@/components/ui";
import { api, dateLabel } from "@/lib/client/api";
import { useAppData } from "@/lib/client/store";

type Report = { id: string; courseSlug: string; courseName: string; contentId: string; title: string; author: string; reporter: string; reason: string; details: string; status: string; version: number; visibility: string; locked: boolean; createdAt: string };
type Appeal = { id: string; courseSlug: string; courseName?: string; title?: string; message: string; status: string; author?: string; createdAt: string };
type Action = { id: string; action?: string; type?: string; reason: string; actor?: string | { displayName: string; username: string }; createdAt: string; courseName?: string };
type Queue = { reports: Report[]; appeals: Appeal[]; actions: Action[] };

export default function ModerationPage() {
  const { canModerate, courses } = useAppData(); const [queue, setQueue] = useState<Queue | null>(null); const [error,setError] = useState<string | null>(null); const [selected,setSelected] = useState<Report | null>(null); const [appeal,setAppeal] = useState<Appeal | null>(null); const [course,setCourse] = useState("");
  const refresh = useCallback(async () => { try { setQueue(await api<Queue>("/moderation")); setError(null); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load moderation."); } }, []);
  useEffect(() => { queueMicrotask(() => void refresh()); },[refresh]);
  const reports = queue?.reports.filter(item => !course || item.courseSlug === course) ?? [];
  return <><PageHeading title="Moderation" description="Review reports, resolve appeals, and inspect recent moderation actions." />{error ? <p className="notice notice-warning" role="alert">{error}</p> : null}{canModerate ? <><div className="split wrap"><label className="field filter-field"><span>Course</span><select className="select" value={course} onChange={event => setCourse(event.target.value)}><option value="">All assigned courses</option>{courses.filter(item => item.role === "STAFF" || canModerate).map(item => <option key={item.id} value={item.slug}>{item.name}</option>)}</select></label><Link className="button" href="/admin">Manage course members</Link></div><Panel title="Reports" action={<Badge>{reports.length}</Badge>}>{!queue ? <p role="status">Loading reports…</p> : reports.length ? <div className="stack">{reports.map(item => <article className="content-card" key={item.id}><div className="split wrap"><h3>{item.title}</h3><Badge tone={item.status === "OPEN" ? "warning" : undefined}>{item.status}</Badge></div><p>{item.reason.replaceAll("_"," ")}: {item.details}</p><div className="meta">{item.courseName} · Author: {item.author} · Reported by {item.reporter} · {dateLabel(item.createdAt)}</div><button className="button" onClick={() => setSelected(item)} type="button">Review report</button></article>)}</div> : <p className="empty-state">No reports to review.</p>}</Panel><Panel title="Appeals"><div className="stack">{queue?.appeals.filter(item => !course || item.courseSlug === course).map(item => <article className="content-card" key={item.id}><div className="split wrap"><strong>{item.title ?? "Contribution appeal"}</strong><Badge>{item.status}</Badge></div><p className="plain-content">{item.message}</p><div className="meta">{item.author} · {dateLabel(item.createdAt)}</div>{item.status === "OPEN" ? <button className="button" onClick={() => setAppeal(item)} type="button">Resolve appeal</button> : null}</article>)}</div>{!queue?.appeals.length ? <p className="empty-state">No appeals.</p> : null}</Panel><Panel title="Recent audit history"><ul className="item-list">{queue?.actions.map(item => <li key={item.id}><strong>{item.action ?? item.type}</strong> · {item.reason}<div className="meta">{typeof item.actor === "string" ? item.actor : item.actor?.displayName} · {dateLabel(item.createdAt)}</div></li>)}</ul>{!queue?.actions.length ? <p className="empty-state">No moderation actions yet.</p> : null}</Panel></> : null}
    <Modal open={Boolean(selected)} onClose={() => setSelected(null)} title="Review report"><AsyncForm label="Apply decision" onCancel={() => setSelected(null)} onSubmit={async form => { if (!selected) return; await api(`/courses/${selected.courseSlug}/moderation`, { body: { contentId:selected.contentId, version:selected.version, reportId:selected.id, action:form.get("action"), reason:form.get("reason") } }); setSelected(null); await refresh(); }}><p>{selected?.title}</p><label className="field"><span>Decision</span><select className="select" name="action"><option value="HIDE">Hide contribution</option><option value="RESTORE">Restore contribution</option><option value="LOCK">Lock contribution</option><option value="UNLOCK">Unlock contribution</option><option value="DISMISS_REPORT">Dismiss report</option></select></label><label className="field"><span>Reason (required, recorded in audit history)</span><textarea className="textarea" name="reason" required rows={4} maxLength={4000} /></label></AsyncForm></Modal>
    <Modal open={Boolean(appeal)} onClose={() => setAppeal(null)} title="Resolve appeal"><AsyncForm label="Resolve appeal" onSubmit={async form => { if (!appeal) return; await api(`/courses/${appeal.courseSlug}/appeals/${appeal.id}`, { body: { status:form.get("status"), resolution:form.get("resolution") } }); setAppeal(null); await refresh(); }}><p>{appeal?.message}</p><label className="field"><span>Decision</span><select className="select" name="status"><option value="UPHELD">Uphold takedown</option><option value="OVERTURNED">Overturn takedown and restore</option></select></label><label className="field"><span>Resolution reason</span><textarea className="textarea" name="resolution" required rows={4} /></label></AsyncForm></Modal></>;
}
