"use client";

import { useCallback, useEffect, useState } from "react";
import { PageHeading } from "@/components/page-heading";
import { AsyncForm, Badge, Modal, Panel } from "@/components/ui";
import { api, dateLabel, type Attempt } from "@/lib/client/api";

export default function PracticeHistoryPage() {
  const [attempts, setAttempts] = useState<Attempt[]>([]); const [confirm,setConfirm] = useState(false); const [error,setError] = useState<string | null>(null); const [loading,setLoading] = useState(true); const [cursor,setCursor] = useState<string | null>(null); const [loadingMore,setLoadingMore] = useState(false);
  const refresh = useCallback(async () => { try { const result = await api<{ attempts: Attempt[]; nextCursor: string | null }>("/me/practice?limit=100"); setAttempts(result.attempts); setCursor(result.nextCursor); setError(null); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load history."); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => void refresh()); }, [refresh]);
  return <><PageHeading title="My practice" description="Your private answer history. Question authors and course staff cannot view it." action={attempts.length ? <button className="button button-danger" onClick={() => setConfirm(true)} type="button">Clear history</button> : undefined} />{error ? <p className="notice notice-warning" role="alert">{error}</p> : null}<Panel title="Attempt history">{loading ? <p role="status">Loading history…</p> : attempts.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Assessment</th><th>Question</th><th>Response</th><th>Result</th><th>When</th></tr></thead><tbody>{attempts.map(item => <tr key={item.id}><td>{item.assessment}</td><td>{item.prompt}</td><td className="plain-content">{typeof item.response === "string" ? item.response : JSON.stringify(item.response)}</td><td><Badge tone={item.result.toUpperCase() === "CORRECT" ? "success" : item.result.toUpperCase() === "INCORRECT" ? "danger" : "warning"}>{item.result}</Badge></td><td>{dateLabel(item.createdAt ?? item.when)}</td></tr>)}</tbody></table></div> : <p className="empty-state">No practice attempts yet. Answer a sample question to begin.</p>}</Panel>{cursor ? <button className="button" disabled={loadingMore} type="button" onClick={async () => { setLoadingMore(true); try { const result = await api<{ attempts: Attempt[]; nextCursor: string | null }>(`/me/practice?limit=100&cursor=${encodeURIComponent(cursor)}`); setAttempts(current => [...current, ...result.attempts]); setCursor(result.nextCursor); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load more history."); } finally { setLoadingMore(false); } }}>{loadingMore ? "Loading..." : "Load older attempts"}</button> : null}<Modal onClose={() => setConfirm(false)} open={confirm} title="Clear practice history?"><AsyncForm label="Clear history" onCancel={() => setConfirm(false)} onSubmit={async () => { await api("/me/practice", { method: "DELETE", body: {} }); await refresh(); setConfirm(false); }}><p>This permanently removes all your saved attempts from openTJ.</p></AsyncForm></Modal></>;
}
